ImfuyoRanch/Controllers/ItemsController.cs
using ImfuyoRanch.Models;
using ImfuyoRanch.Services;
using Shopping;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImfuyoRanch.Controllers
{
    public class ItemsController : Controller
    {
        private Item_Service item;
        Category_Service category_Service;
        public ItemsController()
        {
            this.item = new Item_Service();
            this.category_Service = new Category_Service();
        }
        public ActionResult Index()
        {
            return View(item.GetItems());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.GetItem(id) != null)
                return View(item.GetItem(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult Create()
        {
            ViewBag.Category_ID = new SelectList(category_Service.GetCategories(), "Category_ID", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item model, HttpPostedFileBase photoUpload)
        {
            ViewBag.Category_ID = new SelectList(category_Service.GetCategories(), "Category_ID", "Name");
            byte[] photo = null;
            photo = new byte[photoUpload.ContentLength];
            photoUpload.InputStream.Read(photo, 0, photoUpload.ContentLength);
            model.Picture = photo;

            if (ModelState.IsValid)
            {
                item.AddItem(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int? id)
        {
            ViewBag.Category_ID = new SelectList(category_Service.GetCategories(), "Category_ID", "Name");
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.GetItem(id) != null)
                return View(item.GetItem(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item model, HttpPostedFileBase img_upload)
        {
            byte[] Models = null;
            Models = new byte[img_upload.ContentLength];
            img_upload.InputStream.Read(Models, 0, img_upload.ContentLength);
            model.Picture = Models;
            if (ModelState.IsValid)
            {
                item.UpdateItem(model);
                return RedirectToAction("Index");
            }
            ViewBag.Category_ID = new SelectList(category_Service.GetCategories(), "Category_ID", "Name");
            return View(model);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.GetItem(id) != null)
                return View(item.GetItem(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            item.RemoveItem(item.GetItem(id));
            return RedirectToAction("Index");
        }
    }
}

ImfuyoRanch/Controllers/OrdersController.cs
using ImfuyoRanch.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImfuyoRanch.Controllers
{
    public class OrdersController : Controller
    {
        private Order_Service order_Service;

        public OrdersController()
        {
            this.order_Service = new Order_Service();
        }

        //Customer orders
        public ActionResult Customer_Orders(string id)
        {
            var userName = User.Identity.GetUserName();
            if (User.IsInRole("Customer"))
            {
                if (String.IsNullOrEmpty(id) || id == "all")
                {
                    ViewBag.Status = "All";
                    return View(order_Service.GetOrders().Where(x=>x.Email==userName));
                }
                else
                {
                    ViewBag.Status = id;
                    return View(order_Service.GetOrders(id).Where(x => x.Email == userName));
                }
            }
            else
            {
                if (String.IsNullOrEmpty(id) || id == "all")
                {
                    ViewBag.Status = "All";
                    return View(order_Service.GetOrders());
                }
                else
                {
                    ViewBag.Status = id;
                    return View(order_Service.GetOrders(id));
                }
            }

          
        }
        public ActionResult New_Orders(string id)
        {
            if (String.IsNullOrEmpty(id) || id == "all")
            {
                ViewBag.Status = "All";
                return View(order_Service.GetOrders());
            }
            else
            {
                ViewBag.Status = id;
                return View(order_Service.GetOrders(id));
            }
        }
        public ActionResult Order_Details(string id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (order_Service.GetOrder(id) != null)
                return View(order_Service.GetOrderDetail(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult Order_Tracking(string id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (order_Service.GetOrder(id) != null)
            {
                ViewBag.Order = order_Service.GetOrder(id);
                return View(order_Service.GetOrderTrackingReport(id));
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }

        public ActionResult Mark_As_Packed(string id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (order_Service.GetOrder(id) != null)
            {
                order_Service.MarkOrderAsPacked(id);
                return RedirectToAction("Order_Details", new { id = id });
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult schedule_OrderDelivery(string id, DateTime date)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (order_Service.GetOrder(id) != null)
            {
                order_Service.schedule_OrderDelivery(id, date);
                return RedirectToAction("Order_Details", new { id = id });
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        //account orders
        public ActionResult Order_History()
        {
            return View(order_Service.GetOrders().Where(x => x.Customer.Email == User.Identity.Name));
        }
    }
}

ImfuyoRanch/Controllers/ShoppingController.cs
using ImfuyoRanch.Models;
using ImfuyoRanch.Services;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using Shopping;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ImfuyoRanch.Controllers
{
    public class ShoppingController : Controller
    {
        private Cart_Service cart_Service;
        private Item_Service item_Service;
        private Customer_Service customer_Service;
        private Order_Service order_Service;
        private Affiliate_Service affiliate_Service;
        private Department_Service department_Service;
        private Address_Service address_Service;

        private ApplicationDbContext db = new ApplicationDbContext();

        public ShoppingController()
        {
            this.cart_Service = new Cart_Service();
            this.item_Service = new Item_Service();
            this.customer_Service = new Customer_Service();
            this.order_Service = new Order_Service();
            this.affiliate_Service = new Affiliate_Service();
            this.department_Service = new Department_Service();
            this.address_Service = new Address_Service();
        }
        public ActionResult Index(int? id)
        {
            var items_results = new List<Item>();
            try
            {
                if (id != null)
                {
                    if (id == 0)
                    {
                        items_results = item_Service.GetItems();
                        ViewBag.Department = "All Departments";
                    }
                    else
                    {
                        items_results = item_Service.GetItems().Where(x => x.Category.Department_ID == (int)id).ToList();
                        ViewBag.Department = department_Service.GetDepartment(id).Department_Name;
                    }
                }
                else
                {
                    items_results = item_Service.GetItems();
                    ViewBag.Department = "All Departments";
                }
            }
            catch (Exception ex) { }
            return View(items_results);
        }
        public ActionResult add_to_cart(int id)
        {
            var item = item_Service.GetItem(id);
            if (item != null)
            {
                cart_Service.AddItemToCart(id);
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult remove_from_cart(string id)
        {
            var item = cart_Service.GetCartItems().FirstOrDefault(x => x.cart_item_id == id);
            if (item != null)
            {
                cart_Service.RemoveItemFromCart(id: id);
                return RedirectToAction("ShoppingCart");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult ShoppingCart()
        {
            ViewBag.Total = cart_Service.GetCartTotal(cart_Service.GetCartID());
            ViewBag.TotalQTY = cart_Service.GetCartItems().FindAll(x => x.cart_id == cart_Service.GetCartID()).Sum(q => q.quantity);
            return View(cart_Service.GetCartItems().FindAll(x => x.cart_id == cart_Service.GetCartID()));
        }
        [HttpPost]
        public ActionResult ShoppingCart(List<Cart_Item> items)
        {
            foreach (var i in items)
            {
                cart_Service.UpdateCart(i.cart_item_id, i.quantity);
            }
            return RedirectToAction("ShoppingCart");
        }
        public ActionResult countCartItems()
        {
            int qty = cart_Service.GetCartItems().Sum(x => x.quantity);
            return Content(qty.ToString());
        }
        public ActionResult Checkout()
        {
            if (cart_Service.GetCartItems().Count == 0)
            {
                ViewBag.Err = "Opps... you should have atleat one cart item, please shop a few items";
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("HowToGetMyOrder");
        }
        [Authorize]
        public ActionResult HowToGetMyOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult HowToGetMyOrder(string street_number, string street_name, string City, string State, string ZipCode, string Country)
        {
            Session["street_number"] = street_number;
            Session["street_name"] = street_name;
            Session["City"] = City;
            Session["State"] = State;
            Session["ZipCode"] = ZipCode;
            Session["Country"] = Country;
            return RedirectToAction("PlaceOrder", new { id = "deliver" });
        }
        [Authorize]
        public ActionResult PlaceOrder(string id)
        {
            var userName = User.Identity.GetUserName();
            /* Find the details of the customer placing the order*/
            var customer = db.Customers.Where(x=>x.Email==userName).FirstOrDefault();
            /* Place the order */
            order_Service.AddOrder(customer);
            /* Get the last placed order by the cus.tomer */
            var order = order_Service.GetOrders()
                .FindAll(x => x.Email == customer.Email)
                .OrderByDescending(x => x.date_created)
                .FirstOrDefault();
            /* If the customer requests delivery, save order address */
            if (id == "deliver")
            {
                address_Service.AddShippingAddress(new Shipping_Address()
                {
                    Order_ID = order.Order_ID,
                    street_number = Convert.ToInt16(Session["street_number"].ToString()),
                    street_name = Session["street_name"].ToString(),
                    City = Session["City"].ToString(),
                    State = Session["State"].ToString(),
                    ZipCode = Session["ZipCode"].ToString(),
                    Country = Session["Country"].ToString(),

                    Building_Name = "",
                    Floor = "",
                    Contact_Number = "",
                    Comments = "",
                    Address_Type = ""
                });
            }
            /* Migrate cart items to map as order items */
            order_Service.AddOrderItems(order, cart_Service.GetCartItems());
            /* Empty the cart items */
            cart_Service.EmptyCart();
            /* Update Order Tracking Report */
            order_Service.AddOrderTrackingReport(new Order_Tracking()
            {
                order_ID = order.Order_ID,
                date = DateTime.Now,
                status = "Awaiting Payment",
                Recipient = ""
            });

            
            //Redirect to payment
            return RedirectToAction("Payment", new { id = order.Order_ID });
        }
        
        public ActionResult Payment(string id)
        {
            return View(order_Service.GetOrderDetail(id));
        }
        public ActionResult Secure_Payment(string id)
        {
            var order = order_Service.GetOrder(id);
            return Redirect(PaymentLink(order_Service.GetOrderTotal(order.Order_ID).ToString(), "Order Payment | Order No: " + order.Order_ID, order.Order_ID));
        }
        public ActionResult Return_Url(string id)
        {
            var order = order_Service.GetOrder(id);

            ViewBag.Order = order;
            ViewBag.Account = customer_Service.GetCustomer(order.Email);
            ViewBag.Address = address_Service.GetOrderAddresses().Find(x => x.Order_ID == order.Order_ID);
            ViewBag.Items = order_Service.GetOrderItems(order.Order_ID);
            ViewBag.Total = order_Service.GetOrderTotal(order.Order_ID);
            return View();
        }
        public ActionResult Payment_Successfull(string id)
        {
            try
            {
                var order = order_Service.GetOrder(id);
                order_Service.Update_Stock(id);
                order_Service.AddPayment(order.Order_ID);
                order_Service.EstimateDeliveryDateReport(order);


                if (affiliate_Service.GetAffiliateJoiners().FirstOrDefault(x => x.New_Customer_Email == order.Email) != null)
                { /* deposit benefits */
                    affiliate_Service.PayAffiliates(order.Email, (decimal)order_Service.GetOrderTotal(order.Order_ID));
                }
            }
            catch (Exception ex) { }
            return View();
        }

        public string PaymentLink(string totalCost, string paymentSubjetc, string order_id)
        {

            string paymentMode = ConfigurationManager.AppSettings["PaymentMode"], site, merchantId, merchantKey, returnUrl, cancelUrl, PF_NotifyURL;

            if (paymentMode == "test")
            {
                site = "https://sandbox.payfast.co.za/eng/process?";
                merchantId = "10005631";
                merchantKey = "znbndc034nb6b";
            }
            else if (paymentMode == "live")
            {
                site = "https://www.payfast.co.za/eng/process?";
                merchantId = ConfigurationManager.AppSettings["PF_MerchantID"];
                merchantKey = ConfigurationManager.AppSettings["PF_MerchantKey"];
            }
            else
            {
                throw new InvalidOperationException("Payment method unknown.");
            }
            var stringBuilder = new StringBuilder();
            PF_NotifyURL = Url.Action("https://stackoverflow.com/questions/22374593/extracting-data-from-pdf417-such-as-drivers-license");
            returnUrl = Url.Action("https://stackoverflow.com/questions/22374593/extracting-data-from-pdf417-such-as-drivers-license");

ImfuyoRanch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-2.2.3/pdfmake-0.1.18/dt-1.10.12/af-2.1.2/b-1.2.2/b-colvis-1.2.2/b-html5-1.2.2/b-print-1.2.2/fc-3.2.2/fh-3.1.2/kt-2.1.3/r-2.1.0/rr-1.1.2/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #337ab7 !important; color: white !important;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Imfuyo Ranch", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @{ var department_Service = new ImfuyoRanch.Services.Department_Service();
                var cart_Service = new ImfuyoRanch.Services.Cart_Service();
                double total = 0;
                }
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">



                        @if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-list"></span> Management <span class="caret"></span></a>
                                <ul class="dropdown-menu mega scrollable-menu">
                                    <ul class="sub-menu">
                                        <li class="dropdown-header">Manage Departments</li>
                                        <li>@Html.ActionLink("Add New Department", "Create", "Departments")</li>
                                        <li>@Html.ActionLink("View all Departments", "Index", "Departments")</li>
                                        <li class="dropdown-header">Manage Categories</li>
                                        <li>@Html.ActionLink("Add New Category", "Create", "Categories")</li>
                                        <li>@Html.ActionLink("View all Categories", "Index", "Categories")</li>
                                    </ul>



                                    <ul class="sub-menu">
                                        <li class="dropdown-header">Product Management</li>
                                        <li>@Html.ActionLink("Add New Item", "Create", "Items")</li>
                                        <li>@Html.ActionLink("View all Items", "Index", "Items")</li>
                                    </ul>
                                    <ul class="sub-menu">
                                        <li class="dropdown-header">Orders</li>
                                        <li>@Html.ActionLink("View all Orders", "Customer_Orders", "Orders")</li>

                                    </ul>

                                </ul>
                            </li>
                        }
                        else
                        {
                            if (User.Identity.IsAuthenticated == true)
                            {
                                <li>@Html.ActionLink("My Details", "Index", "Customers")</li>
                                <li>@Html.ActionLink("Order History", "Customer_Orders", "Orders")</li>
                            }
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-list"></span> Shop by Category <span class="caret"></span></a>
                                <ul class="dropdown-menu mega scrollable-menu">
                                    <ul class="sub-menu">
                                        <li><a href="@Url.Action("Index","Shopping",new { id = 0})">All Departments</a></li>
                                        @foreach (var department in department_Service.GetDepartments().OrderBy(x => x.Department_Name))
                                        {
                                            <li>
                                                <a href="@Url.Action("Index","Shopping",new { id = department.Department_ID })">@department.Department_Name</a>
                                            </li>
                                        }
                                    </ul>
                                </ul>
                            </li>



                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="fa fa-shopping-cart"></span> Cart (@Html.Action(actionName: "countCartItems", controllerName: "Shopping"))<span class="caret"></span></a>
                                <ul class="dropdown-menu mega">
                                    <ul class="sub-menu">
                                        <table class="table">
                                            <tr style="background: #f3f3f3;">
                                                <th>Item</th>
                                                <th>

                                                </th>
                                                <th style="text-align:center">
                                                    Quantity
                                                </th>
                                                <th>
                                                    Price
                                                </th>
                                                <th style="text-align:center">
                                                    Sub-Total
                                                </th>
                                            </tr>
                                            @if (cart_Service.GetCartItems().Count() == 0)
                                            {
                                                <tr>
                                                    <th colspan="5" style="text-align:center">Your cart is empty</th>
                                                </tr>
                                            }
                                            @foreach (var item in cart_Service.GetCartItems().OrderBy(x => x.Item.Name))
                                            {
                                                <tr>
                                                    <td>
                                                        @if (item.Item.Picture != null)
                                                        {
                                                            var base64 = Convert.ToBase64String(item.Item.Picture);
                                                            var imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                                                            <img src="@imgSrc" width="30" height="30" />}
                                                    </td>
                                                    <td>
                                                        <a href="@Url.Action("Details","Items", new { id=item.Item.ItemCode })">@item.Item.Name</a>
                                                    </td>
                                                    <td style="text-align:center">
                                                        @item.quantity
                                                    </td>
                                                    <td>
                                                        @item.Item.Price.ToString("C")
                                                    </td>
                                                    <td style="text-align:center">
                                                        @{ var subtotal = item.quantity * item.Item.Price;
                                                            total += subtotal; }

                                                        @subtotal.ToString("C")
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td style="text-align:center">
                                                    Total
                                                </td>
                                                <th style="text-align:center">
                                                    @total.ToString("C")
                                                </th>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>
                                                    <a class="btn btn-default" href="@Url.Action("Index","Shopping")">
                                                        <i class="fa fa-list"></i> Shop More
                                                    </a>

                                                </td>
                                                <td>
                                                    <a class="btn btn-default" href="@Url.Action("ShoppingCart", "Shopping")">
                                                        <i class="fa fa-shopping-cart"></i> View Cart
                                                    </a>
                                                </td>
                                                <td>
                                                    @if (cart_Service.GetCartItems().Count() == 0)
                                                    {
                                                        <a class="btn btn-default disabled" href="@Url.Action("Checkout","Shopping")">
                                                            <i class="fa fa-lock"></i> Checkout
                                                        </a> }
                                                    else
                                                    {
                                                        <a class="btn btn-default" href="@Url.Action("Checkout","Shopping")">
                                                            <i class="fa fa-lock"></i> Checkout
                                                        </a>}

                                                </td>
                                            </tr>
                                        </table>
                                    </ul>
                                </ul>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;  @DateTime.Now.Year - Imfuyo Ranch</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
























<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modelId">
  Launch
</button>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
     @using (Html.BeginForm("SetDelivery", "Orders")){
                 <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
              @Html.TextBox("DaliveryDate")
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
     }
  
    </div>
</div>